font_size           16.0
font_family         FiraCode Nerd Font Mono
#font_family         Inconsolata LGC Nerd Font Mono, Regular
bold_font           auto
italic_font         auto
bold_italic_font    auto
disable_ligatures   never

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

window_padding_width 1

shell_integration   no-cursor
cursor_shape        underline

mouse_hide_wait     3.0

copy_on_select      yes

enable_audio_bell   no

sync_to_monitor     no

kitty_mod alt
map ctrl+shift+h show_scrollback
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down
map kitty_mod+m new_tab
map kitty_mod+tab next_tab
map kitty_mod+shift+tab previous_tab
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+q close_tab

background            #202020
foreground            #d0d0d0
cursor                #d0d0d0
selection_background  #303030
color0                #151515
color8                #505050
color1                #ac4142
color9                #ac4142
color2                #7e8d50
color10               #7e8d50
color3                #e5b566
color11               #e5b566
color4                #6c99ba
color12               #6c99ba
color5                #9e4e85
color13               #9e4e85
color6                #7dd5cf
color14               #7dd5cf
color7                #d0d0d0
color15               #f5f5f5
selection_foreground #202020

active_tab_foreground   #D3A04D
active_tab_background   #151515
active_tab_font_style   bold
inactive_tab_foreground #D3A04D
inactive_tab_background #505050
inactive_tab_font_style normal
